import { Metadata } from "next";
import Sidebar from "./Sidebar";
import Topbar from "./Topbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-light text-dark">
        <section className="flex">
          <div className="w-64 max-md:hidden" />
          <Sidebar />
          <div className="w-[calc(100vw-16rem)] flex flex-col">
            <Topbar />
            {children}
          </div>
        </section>
      </body>
    </html>
  );
}
