import { Metadata } from "next";
import Sidebar from "./Sidebar";
import Topbar from "./Topbar";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { API } from "@/utils/constants";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const email = cookies().get("email");
  const token = cookies().get("token");
  if (!email || !token) redirect("/admin/login");

  const req = await fetch(`${API}admin/addcategory`, {
    method: "POST",
    headers: {
      "x-access-token": token.value,
    },
  });
  const res = await req.json();
  if (
    !res.message ||
    res.message.toLowerCase().includes("token is required") ||
    res.message.toLowerCase().includes("invalid token")
  ) {
    redirect("/admin/log-out");
  }

  return (
    <section className="flex">
      <div className="w-64 max-lg:hidden" />
      <Sidebar />
      <div className="w-full lg:max-w-[calc(100vw-16rem)] lg:w-[calc(100vw-16rem)] overflow-x-auto flex flex-col min-h-[95vh] bg-light-gray h-full">
        <Topbar />
        {children}
        <div className="py-2" />
      </div>
    </section>
  );
}
